export const DOMAINS = [
    // --- TECH & CLOUD SERVICES ---
    'google.com',
    'gmail.com',
    'drive.google.com',
    'docs.google.com',
    'microsoft.com',
    'office.com',
    'live.com',
    'outlook.com',
    'hotmail.com',
    'apple.com',
    'icloud.com',
    'itunes.com',
    'amazon.com',
    'aws.amazon.com',
    'adobe.com',
    'dropbox.com',
    'wetransfer.com',
    'zoom.us',
    'salesforce.com',
    'oracle.com',
    'ibm.com',
    'cisco.com',
    'intel.com',
    'hp.com',
    'dell.com',
    'lenovo.com',
    'github.com',
    'gitlab.com',
    'bitbucket.org',
    'stackoverflow.com',
    'godaddy.com',
    'namecheap.com',
    'cloudflare.com',

    // --- FINANCIAL INSTITUTIONS (US/Global) ---
    'paypal.com',
    'venmo.com',
    'cash.app',
    'zellepay.com',
    'westernunion.com',
    'chase.com',
    'bankofamerica.com',
    'wellsfargo.com',
    'citibank.com',
    'americanexpress.com',
    'capitalone.com',
    'usbank.com',
    'pnc.com',
    'td.com',
    'rbc.com',
    'scotiabank.com',
    'bmo.com', // Canada
    'barclays.co.uk',
    'hsbc.com',
    'lloydsbank.com',
    'santander.com', // UK/EU
    'fidelity.com',
    'schwab.com',
    'vanguard.com',
    'morganstanley.com',
    'goldmansachs.com',
    'blackrock.com',
    'mastercard.com',
    'visa.com',
    'discover.com',
    'stripe.com',
    'square.com',
    'wise.com',
    'revolut.com',
    'payoneer.com',

    // --- CRYPTOCURRENCY & WEB3 (High Risk) ---
    'coinbase.com',
    'binance.com',
    'kraken.com',
    'gemini.com',
    'crypto.com',
    'kucoin.com',
    'bitfinex.com',
    'huobi.com',
    'okx.com',
    'bybit.com',
    'blockchain.com',
    'etherscan.io',
    'bscscan.com',
    'metamask.io',
    'trustwallet.com',
    'phantom.app',
    'exodus.com',
    'trezor.io',
    'ledger.com',
    'opensea.io',
    'rarible.com',
    'magiceden.io',
    'uniswap.org',
    'pancakeswap.finance',
    '1inch.io',

    // --- SOCIAL MEDIA & MESSAGING ---
    'facebook.com',
    'instagram.com',
    'messenger.com',
    'whatsapp.com',
    'twitter.com',
    'x.com',
    'linkedin.com',
    'snapchat.com',
    'tiktok.com',
    'pinterest.com',
    'reddit.com',
    'tumblr.com',
    'telegram.org',
    'discord.com',
    'slack.com',
    'skype.com',
    'wechat.com',
    'line.me',
    'signal.org',

    // --- RETAIL & E-COMMERCE ---
    'walmart.com',
    'target.com',
    'bestbuy.com',
    'costco.com',
    'homedepot.com',
    'lowes.com',
    'macys.com',
    'ebay.com',
    'etsy.com',
    'shopify.com',
    'wayfair.com',
    'aliexpress.com',
    'alibaba.com',
    'rakuten.com',
    'nike.com',
    'adidas.com',
    'gucci.com',
    'louisvuitton.com',

    // --- STREAMING & GAMING ---
    'netflix.com',
    'hulu.com',
    'disneyplus.com',
    'hbo.com',
    'spotify.com',
    'youtube.com',
    'twitch.tv',
    'steampowered.com',
    'roblox.com',
    'epicgames.com',
    'ubisoft.com',
    'playstation.com',
    'xbox.com',
    'nintendo.com',
    'ea.com',
    'blizzard.com',
    'minecraft.net',
    'riotgames.com',
    'battle.net',

    // --- LOGISTICS & TRAVEL ---
    'dhl.com',
    'fedex.com',
    'ups.com',
    'usps.com',
    'royalmail.com',
    'dpd.com',
    'canadapost.ca',
    'auspost.com.au',
    'blue-dart.com',
    'uber.com',
    'lyft.com',
    'airbnb.com',
    'booking.com',
    'expedia.com',
    'tripadvisor.com',
    'delta.com',
    'united.com',
    'aa.com',
    'ryanair.com',

    // --- GOVERNMENT & TAX (Seasonal Phishing) ---
    'irs.gov',
    'ssa.gov',
    'medicare.gov',
    'usa.gov',
    'hmrc.gov.uk',
    'cra-arc.gc.ca',

    // --- TELECOM & UTILITIES ---
    'att.com',
    'verizon.com',
    't-mobile.com',
    'sprint.com',
    'comcast.com',
    'xfinity.com',
    'spectrum.com',
    'centurylink.com',
    'vodafone.com',
    'orange.com',
    'telefonica.com',
    'bt.com',
];
